"""store recovery failure context

Revision ID: a80425f69fb4
Revises: 809c126ae54b
Create Date: 2026-08-28 20:37:34.183014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80425f69fb4'
down_revision: Union[str, Sequence[str], None] = '809c126ae54b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('failure_code', sa.String(length=100), nullable=True))
    op.add_column('recovery_cases', sa.Column('failure_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'failure_reason')
    op.drop_column('recovery_cases', 'failure_code')
    # ### end Alembic commands ###
