"""add recovery outcome fields

Revision ID: b52949927497
Revises: 12aaef098c42
Create Date: 2026-08-27 18:20:32.201951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52949927497'
down_revision: Union[str, Sequence[str], None] = '12aaef098c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('recovered_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('recovery_cases', sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'recovered_at')
    op.drop_column('recovery_cases', 'recovered_amount')
    # ### end Alembic commands ###
